config/routes.rb
Cms::Application.routes.draw do

  resources :navigations


  mount UeditorRails::Engine => '/ueditor'

  resources :pages, :only => [:show]

  namespace :admin do
    resources :companies
    resources :pages
    resources :ueditor do
      collection do
        post :images
        post :upload
      end
    end
    resources :images
  end

  scope "/admin/" do 
    resources :snippets
    resources :templates
    resources :navigations
  end

  match "home/work"  => "home#work"
  match "home/intro" => "home#intro"
  match "home/idea"  => "home#idea"
  match "/admin"      => "companies#index", :module => :admin

  root :to => "home#index"
end

app/models/navigation.rb
class Navigation < ActiveRecord::Base
  attr_accessible :name, :url

  def absoulte_url
    pattern = /^\//
    match = pattern.match(url)
    if match
      "http://rpm.fw.tv:8888#{url}"
    else
      "http://rpm.fw.tv:8888/#{url}" 
    end
  end
end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  layout 'admin'

  # GET /navigations
  # GET /navigations.json
  def index
    @navigations = Navigation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @navigations }
    end
  end

  # GET /navigations/1
  # GET /navigations/1.json
  def show
    @navigation = Navigation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/new
  # GET /navigations/new.json
  def new
    @navigation = Navigation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/1/edit
  def edit
    @navigation = Navigation.find(params[:id])
  end

  # POST /navigations
  # POST /navigations.json
  def create
    @navigation = Navigation.new(params[:navigation])

    respond_to do |format|
      if @navigation.save
        format.html { redirect_to @navigation, notice: 'Navigation was successfully created.' }
        format.json { render json: @navigation, status: :created, location: @navigation }
      else
        format.html { render action: "new" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /navigations/1
  # PUT /navigations/1.json
  def update
    @navigation = Navigation.find(params[:id])

    respond_to do |format|
      if @navigation.update_attributes(params[:navigation])
        format.html { redirect_to @navigation, notice: 'Navigation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navigations/1
  # DELETE /navigations/1.json
  def destroy
    @navigation = Navigation.find(params[:id])
    @navigation.destroy

    respond_to do |format|
      format.html { redirect_to navigations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/navigations_helper.rb
module NavigationsHelper
end

app/views/navigations/_form.html.erb
<%= form_for(@navigation) do |f| %>
  <% if @navigation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@navigation.errors.count, "error") %> prohibited this navigation from being saved:</h2>

      <ul>
      <% @navigation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/navigations/edit.html.erb
<h1>Editing navigation</h1>

<%= render 'form' %>

<%= link_to 'Show', @navigation %> |
<%= link_to 'Back', navigations_path %>

app/views/navigations/index.html.erb
<h3>Listing navigations</h3>

<table class='table'>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @navigations.each do |navigation| %>
  <tr>
    <td><%= navigation.name %></td>
    <td><%= navigation.url %></td>
    <td><%= link_to 'Show', navigation %></td>
    <td><%= link_to 'Edit', edit_navigation_path(navigation) %></td>
    <td><%= link_to 'Destroy', navigation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Navigation', new_navigation_path %>

app/views/navigations/new.html.erb
<h1>New navigation</h1>

<%= render 'form' %>

<%= link_to 'Back', navigations_path %>

app/views/navigations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @navigation.name %>
</p>

<p>
  <b>Url:</b>
  <%= @navigation.url %>
</p>


<%= link_to 'Edit', edit_navigation_path(@navigation) %> |
<%= link_to 'Back', navigations_path %>