config/routes.rb
Cms::Application.routes.draw do

  resources :navigations


  mount UeditorRails::Engine => '/ueditor'

  resources :pages, :only => [:show]

  namespace :admin do
    resources :companies
    resources :pages
    resources :ueditor do
      collection do
        post :images
        post :upload
      end
    end
    resources :images
  end

  scope "/admin/" do 
    resources :snippets
    resources :templates
    resources :navigations
  end

  match "home/work"  => "home#work"
  match "home/intro" => "home#intro"
  match "home/idea"  => "home#idea"
  match "/admin"      => "companies#index", :module => :admin

  root :to => "home#index"
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :context, :description, :name, :stype

  def method_missing(name, *args)
    method_name = name.to_s
    if method_name['viewer'] && self.class.column_names.include?(method_name.split("_").first)
      send(method_name.split("_").first)
    else
      super
    end
  end

  def context_viewer
    html = CodeRay.scan(self.context, :html).div(:line_numbers => :table)
    html.html_safe 
  end

  class << self
    def t(key)
      I18n.t("activerecord.attributes.snippet.#{key.to_s}")
    end

    def serialize_columns
      [:name, :description, :context, :stype]
    end
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < AdminController
  layout 'admin'
  
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(params[:snippet])
    @snippet.stype = 'customer'

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<%= form_for(@snippet, :html => { :class => 'col-md-8' }) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_field :description , :class => 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :context %><br />
    <%= f.text_area :context, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'submit', :class => 'btn btn-primary' %>
    <%= link_to 'Back', snippets_path %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h3>Editing snippet</h3>

<%= render 'form' %>

app/views/snippets/index.html.erb
<h3>snippets</h3>

<table class='table'>
  <tr>
    <th>名字</th>
    <th>描述</th>
    <th>类型</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.name %></td>
    <td><%= snippet.description %></td>
    <td><%= snippet.stype %></td>
    <td><%= link_to 'Show', snippet %></td>
    <td> 
      <% if snippet.stype != 'system' %> 
        <%= link_to 'Edit', edit_snippet_path(snippet) %> 
      <% end %>
    </td>
    <td> 
      <% if snippet.stype != 'system' %> 
        <%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h3>New snippet</h3>

<%= render 'form' %>

app/views/snippets/show.html.erb
<div id="notice"><%= notice %></div>

<% Snippet.serialize_columns.each do |column| %>
  <div class='row'>
  <div class="col-md-2">
    <label for="name"><%=Snippet.t(column) %></label>
  </div>
  <div class="col-md-10">
    <% if column.to_s == 'context' %>
      <code>
      <%= @snippet.send("#{column.to_s}_viewer") %>
    </code>
  <% else %>
      <%= @snippet.send("#{column.to_s}_viewer") %>
  <% end -%>
  </div>
</div>
<% end -%>
<% if @snippet.stype != 'system' %>
  <%= link_to 'Edit', edit_snippet_path(@snippet), :class => 'btn btn-default' %> |
<% end %>

<%= link_to 'Back', snippets_path, :class => 'btn btn-default' %>