config/routes.rb
Cms::Application.routes.draw do

  resources :navigations


  mount UeditorRails::Engine => '/ueditor'

  resources :pages, :only => [:show]

  namespace :admin do
    resources :companies
    resources :pages
    resources :ueditor do
      collection do
        post :images
        post :upload
      end
    end
    resources :images
  end

  scope "/admin/" do 
    resources :snippets
    resources :templates
    resources :navigations
  end

  match "home/work"  => "home#work"
  match "home/intro" => "home#intro"
  match "home/idea"  => "home#idea"
  match "/admin"      => "companies#index", :module => :admin

  root :to => "home#index"
end

app/views/templates/edit.html.erb
<%= form_tag template_path(@template), :method => 'PUT', :class => 'col-md-10' do %>
  <div class="form-group">
    <label for="name">模板名称</label>
    <%=text_field_tag 'name', '', :class => 'form-control', :value => @template.name, :disabled => true %>
  </div>

  <div class="form-group">
    <label for="context">模板内容</label>
    <code>
    <%=text_area_tag 'context', @template.context, :class => 'form-control', :cols => 30, :rows => 10 %>
    <code>
  </div>

  <div class="actions">
    <%= submit_tag 'Submit', :class => 'btn btn-primary' %>
  </div>

<% end -%>

app/views/templates/index.html.erb
<h3>模板管理</h3>

<%=link_to '创建模板', new_template_path, :class => 'btn btn-primary pull-right' %>
<table class="table">
  <thead>
    <tr>
      <th>名称</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
  <% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td>
      <a href="/admin/templates?name=<%=template.name %>" class='btn btn-default'>Show</a>
      <%=link_to 'Edit', edit_template_path(template), :class => 'btn btn-default'  %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>

app/views/templates/new.html.erb
<%= form_tag templates_path, :class => 'col-md-10' do %>
  <div class="form-group">
    <label for="name">模板名称</label>
    <%=text_field_tag 'name', '', :class => 'form-control' %>
    <span class="help-inline">名字必须是下划线开始，并且只能是英文字母. 如 _header.html.erb </span>
  </div>

  <div class="form-group">
    <label for="context">模板内容</label>
    <%= ueditor_text_tag 'context', '', :class => 'form-control', :cols => 30, :rows => 10 %>
  </div>

  <div class="actions">
    <%= submit_tag 'Submit', :class => 'btn btn-primary' %>
  </div>

<% end -%>

app/views/templates/show.html.erb
<div class="row">
  <div class="col-md-2">
    <label>
      模板名称
    </label>
  </div>
  <div class="col-md-10">
    <%=@template.name %> 
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <label>模板内容</label>
  </div>
  <div class="col-md-10 col-md-offset-2" style="word-wrap: break-word;word-break: normal;">
    <code>
    <%=@template.format_context %>
    </code>
  </div>
</div>

<%=link_to 'Edit', edit_template_path(@template), :class => 'btn btn-primary' %>