config/routes.rb
Cms::Application.routes.draw do

  resources :navigations


  mount UeditorRails::Engine => '/ueditor'

  resources :pages, :only => [:show]

  namespace :admin do
    resources :companies
    resources :pages
    resources :ueditor do
      collection do
        post :images
        post :upload
      end
    end
    resources :images
  end

  scope "/admin/" do 
    resources :snippets
    resources :templates
    resources :navigations
  end

  match "home/work"  => "home#work"
  match "home/intro" => "home#intro"
  match "home/idea"  => "home#idea"
  match "/admin"      => "companies#index", :module => :admin

  root :to => "home#index"
end

app/views/layouts/_nav.html.erb
<div class="inner">
  <h1 id="logo"><a href="/">DOUND STUDIO</a></h1>
  <div id="nav">
    <%= render_nav_list %>
    <div class="bg"></div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>后台管理</title>
<%= stylesheet_link_tag "admin", :media => "all" %>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin">后台管理</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class='pull-right'><a href="#"><span class='glyphicon glyphicon-user'></span>Help</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="">
        <%= link_to I18n.t('company.admin'), admin_companies_path %>
        </li>
        <li>
          <%= link_to '图片管理', admin_images_path %>
        </li>

        <li>
        <%=link_to '页面管理', admin_pages_path %>
        </li>

        <li>
          <%=link_to "代码管理", snippets_path %>
        </li>

        <li>
          <%=link_to "模板管理", templates_path %>
        </li>
        
        <li>
          <%=link_to "导航管理", navigations_path %>
        </li>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header"><%= @header || 'Dashboard' %></h1>
      <%= yield %>
    </div>
  </div>
</div>

<%= javascript_include_tag "admin" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ie6 oldie" lang="zh"><![endif]-->
<!--[if IE 7]><html class="ie7 oldie" lang="zh"><![endif]-->
<!--[if IE 8]><html class="ie8 oldie" lang="zh"><![endif]-->
<!--[if gt IE 8]><!--> <html> <!--<![endif]-->
<head>
<meta http-equiv="x-ua-compatible" content="IE=9" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<%=favicon_link_tag asset_path('ad1.png') %>
<title><%= @company.name %></title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= csrf_meta_tags %>
</head>
<%= yield %>
<%= javascript_include_tag "application" %>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ie6 oldie" lang="zh"><![endif]-->
<!--[if IE 7]><html class="ie7 oldie" lang="zh"><![endif]-->
<!--[if IE 8]><html class="ie8 oldie" lang="zh"><![endif]-->
<!--[if gt IE 8]><!--> <html> <!--<![endif]-->
<head>
<meta http-equiv="x-ua-compatible" content="IE=9" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<%=favicon_link_tag asset_path('ad1.png') %>
<title><%= @company.name %></title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= csrf_meta_tags %>
</head>
<body id="page">
<div id="doc">
  <div id="hd">
    <%=render 'layouts/nav' %>
  </div>
  <%= yield %> 
  <%=render "templates/partials/footer" %> 
</div>
<%= javascript_include_tag "application" %>
</body>
</html>